### ISSUE TITLE
Issue: TNB Crashes when loading .tile files

### ISSUE THREAD

**Issue by golgolak** [TheNoobCompany/WorldQuestTNB#8]
Based on log multiple logs, tnb crashes whenever this file is being loaded - Troll Raid_20_25_11.tile

Also found the following errors:
[S] 11:45:52 - Downloading "Troll Raid\Troll Raid_24_29_11.tile"...
[E] 11:45:52 - DownloadThread()#1: System.Net.WebException: The remote server returned an error: (404) Not Found.
at System.Net.WebClient.DownloadFile(Uri address, String fileName)
at System.Net.WebClient.DownloadFile(String address, String fileName)
at nManager.Helpful.Others.Esaqisaituoj()

[S] 11:46:11 - Downloading "Troll Raid\Troll Raid_25_29_11.tile"...
[E] 11:46:11 - DownloadThread()#1: System.Net.WebException: The remote server returned an error: (404) Not Found.
at System.Net.WebClient.DownloadFile(Uri address, String fileName)
at System.Net.WebClient.DownloadFile(String address, String fileName)
at nManager.Helpful.Others.Esaqisaituoj()

**Comment by golgolak** [comment]
Just to add, this is when loading the group profile or Val/High/Storm profiles.

**Comment by mmalka** [comment]
It's not loaded, it's a 404 error. because there is no tilme at that location.

**Comment by mmalka** [comment]
if you have crash, read my forum signature, nothing to do with that.
